import React from "react";
import Head from "next/head";
import CookieStandHeader from "./header";
import CookieStandMain from "./main";
import CookieStandFooter from "./footer";
import { useState } from "react";

export default function CookieStandAdmin() {
  const [title, setTitle] = useState("Cookie Stand Admin");
  const [branches, setBranches] = useState("0");
  const [path, setPath] = useState("/overview");
  const [page, setPage] = useState("Overview");

  return (
    <div>
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CookieStandHeader header={title} path={path} page={page} />
      <CookieStandMain title={title} setBranches={setBranches} />
      <CookieStandFooter branches={branches} />
    </div>
  );
}
